package com.github.hhhzzzsss.hbot.processes.boxstructure;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;

public class BlockIndex {
	public static final String[] LEAVES = {
			"oak_leaves",
			"spruce_leaves",
			"birch_leaves",
			"jungle_leaves",
			"acacia_leaves",
			"dark_oak_leaves",
	};
	
	public static final String[] WOOD = {
			"oak",
			"spruce",
			"birch",
			"jungle",
			"acacia",
			"dark_oak",
	};
	
	public static final String[] FLOWERS = {
			"dandelion",
			"poppy",
			"blue_orchid",
			"allium",
			"azure_bluet",
			"red_tulip",
			"orange_tulip",
			"white_tulip",
			"pink_tulip",
			"oxeye_daisy",
			"cornflower",
			"lily_of_the_valley",
			"wither_rose",
	};
	
	public static final String[] FLOWERPOTS = {
			"flower_pot",
			"potted_dandelion",
			"potted_poppy",
			"potted_blue_orchid",
			"potted_allium",
			"potted_azure_bluet",
			"potted_red_tulip",
			"potted_orange_tulip",
			"potted_white_tulip",
			"potted_pink_tulip",
			"potted_oxeye_daisy",
			"potted_cornflower",
			"potted_lily_of_the_valley",
			"potted_wither_rose",
			"potted_oak_sapling",
			"potted_spruce_sapling",
			"potted_birch_sapling",
			"potted_jungle_sapling",
			"potted_acacia_sapling",
			"potted_dark_oak_sapling",
			"potted_red_mushroom",
			"potted_brown_mushroom",
			"potted_fern",
			"potted_dead_bush",
			"potted_cactus",
			"potted_bamboo",
	};
	
	public static final String[] TRAPDOORS = {
			"iron_trapdoor",
			"oak_trapdoor",
			"spruce_trapdoor",
			"birch_trapdoor",
			"jungle_trapdoor",
			"acacia_trapdoor",
			"dark_oak_trapdoor",
	};
	
	public static final String[] COUNTER_BLOCKS = {
			"smooth_quartz",
			"smooth_quartz_slab[type=top]",
			"polished_andesite",
			"polished_andesite_slab[type=top]",
			"dark_prismarine",
			"dark_prismarine_slab[type=top]",
			"nether_bricks",
			"nether_brick_slab[type=top]",
	};
	
	public static final String[] TABLE_HEAD_NAMES = {
			"GoodBook1", // Books
			"mattijs", // Winzip
			"NoobMinatorX", // Clock
			"RagMan17", // Rubik's Cube
			"C418", // Jukebox
			"BlockminersTV", // Globe
			"Cardiff", // Bookshelf
			"SpicyTunaRoll9", // Sushi
	};
	
	public static final String[] GEMS = {
			"gold_block",
			"emerald_block",
			"diamond_block",
			"lapis_block",
	};
	
	public static final String[] VAULT_HEAD_NAMES = {
			"MrSnowDK", // Money Bag
			"Cypiea", // Ender Pearl
			"BizepsPunch", // Diamond Ore
			"Chaochris", // Ender Crystal
			"StackedGold", // Gold Block
			"QuinnSect", // Companion Cube
			"ElMarcosFTW", // Chest
			"Tom25W", // Golden Chest
			"Variable", // Technical Device
	};
	
	public static final Item[] FRIDGE_ITEMS = {
			new Item("potion", "{Potion:\"minecraft:water\"}"),
			new Item("apple"),
			new Item("mushroom_stew"),
			new Item("bread"),
			new Item("porkchop"),
			new Item("cooked_porkchop"),
			new Item("golden_apple"),
			new Item("cod"),
			new Item("salmon"),
			new Item("cooked_cod"),
			new Item("cooked_salmon"),
			new Item("cake"),
			new Item("cookie"),
			new Item("melon_slice"),
			new Item("dried_kelp"),
			new Item("beef"),
			new Item("cooked_beef"),
			new Item("chicken"),
			new Item("cooked_chicken"),
			new Item("carrot"),
			new Item("potato"),
			new Item("baked_potato"),
			new Item("golden_carrot"),
			new Item("pumpkin_pie"),
			new Item("rabbit"),
			new Item("cooked_rabbit"),
			new Item("rabbit_stew"),
			new Item("mutton"),
			new Item("cooked_mutton"),
			new Item("chorus_fruit"),
			new Item("beetroot"),
			new Item("beetroot_soup"),
			new Item("sweet_berries"),
	};

	public static final String[] ITEMS = {
			"air",
			"stone",
			"granite",
			"polished_granite",
			"diorite",
			"polished_diorite",
			"andesite",
			"polished_andesite",
			"grass_block",
			"dirt",
			"coarse_dirt",
			"podzol",
			"cobblestone",
			"oak_planks",
			"spruce_planks",
			"birch_planks",
			"jungle_planks",
			"acacia_planks",
			"dark_oak_planks",
			"oak_sapling",
			"spruce_sapling",
			"birch_sapling",
			"jungle_sapling",
			"acacia_sapling",
			"dark_oak_sapling",
			"bedrock",
			"sand",
			"red_sand",
			"gravel",
			"gold_ore",
			"iron_ore",
			"coal_ore",
			"oak_log",
			"spruce_log",
			"birch_log",
			"jungle_log",
			"acacia_log",
			"dark_oak_log",
			"stripped_oak_log",
			"stripped_spruce_log",
			"stripped_birch_log",
			"stripped_jungle_log",
			"stripped_acacia_log",
			"stripped_dark_oak_log",
			"stripped_oak_wood",
			"stripped_spruce_wood",
			"stripped_birch_wood",
			"stripped_jungle_wood",
			"stripped_acacia_wood",
			"stripped_dark_oak_wood",
			"oak_wood",
			"spruce_wood",
			"birch_wood",
			"jungle_wood",
			"acacia_wood",
			"dark_oak_wood",
			"oak_leaves",
			"spruce_leaves",
			"birch_leaves",
			"jungle_leaves",
			"acacia_leaves",
			"dark_oak_leaves",
			"sponge",
			"wet_sponge",
			"glass",
			"lapis_ore",
			"lapis_block",
			"dispenser",
			"sandstone",
			"chiseled_sandstone",
			"cut_sandstone",
			"note_block",
			"powered_rail",
			"detector_rail",
			"sticky_piston",
			"cobweb",
			"grass",
			"fern",
			"dead_bush",
			"seagrass",
			"sea_pickle",
			"piston",
			"white_wool",
			"orange_wool",
			"magenta_wool",
			"light_blue_wool",
			"yellow_wool",
			"lime_wool",
			"pink_wool",
			"gray_wool",
			"light_gray_wool",
			"cyan_wool",
			"purple_wool",
			"blue_wool",
			"brown_wool",
			"green_wool",
			"red_wool",
			"black_wool",
			"dandelion",
			"poppy",
			"blue_orchid",
			"allium",
			"azure_bluet",
			"red_tulip",
			"orange_tulip",
			"white_tulip",
			"pink_tulip",
			"oxeye_daisy",
			"cornflower",
			"lily_of_the_valley",
			"wither_rose",
			"brown_mushroom",
			"red_mushroom",
			"gold_block",
			"iron_block",
			"oak_slab",
			"spruce_slab",
			"birch_slab",
			"jungle_slab",
			"acacia_slab",
			"dark_oak_slab",
			"stone_slab",
			"smooth_stone_slab",
			"sandstone_slab",
			"cut_sandstone_slab",
			"petrified_oak_slab",
			"cobblestone_slab",
			"brick_slab",
			"stone_brick_slab",
			"nether_brick_slab",
			"quartz_slab",
			"red_sandstone_slab",
			"cut_red_sandstone_slab",
			"purpur_slab",
			"prismarine_slab",
			"prismarine_brick_slab",
			"dark_prismarine_slab",
			"smooth_quartz",
			"smooth_red_sandstone",
			"smooth_sandstone",
			"smooth_stone",
			"bricks",
			"tnt",
			"bookshelf",
			"mossy_cobblestone",
			"obsidian",
			"torch",
			"end_rod",
			"chorus_plant",
			"chorus_flower",
			"purpur_block",
			"purpur_pillar",
			"purpur_stairs",
			"spawner",
			"oak_stairs",
			"chest",
			"diamond_ore",
			"diamond_block",
			"crafting_table",
			"farmland",
			"furnace",
			"ladder",
			"rail",
			"cobblestone_stairs",
			"lever",
			"stone_pressure_plate",
			"oak_pressure_plate",
			"spruce_pressure_plate",
			"birch_pressure_plate",
			"jungle_pressure_plate",
			"acacia_pressure_plate",
			"dark_oak_pressure_plate",
			"redstone_ore",
			"redstone_torch",
			"stone_button",
			"snow",
			"ice",
			"snow_block",
			"cactus",
			"clay",
			"jukebox",
			"oak_fence",
			"spruce_fence",
			"birch_fence",
			"jungle_fence",
			"acacia_fence",
			"dark_oak_fence",
			"pumpkin",
			"carved_pumpkin",
			"netherrack",
			"soul_sand",
			"glowstone",
			"jack_o_lantern",
			"oak_trapdoor",
			"spruce_trapdoor",
			"birch_trapdoor",
			"jungle_trapdoor",
			"acacia_trapdoor",
			"dark_oak_trapdoor",
			"infested_stone",
			"infested_cobblestone",
			"infested_stone_bricks",
			"infested_mossy_stone_bricks",
			"infested_cracked_stone_bricks",
			"infested_chiseled_stone_bricks",
			"stone_bricks",
			"mossy_stone_bricks",
			"cracked_stone_bricks",
			"chiseled_stone_bricks",
			"brown_mushroom_block",
			"red_mushroom_block",
			"mushroom_stem",
			"iron_bars",
			"glass_pane",
			"melon",
			"vine",
			"oak_fence_gate",
			"spruce_fence_gate",
			"birch_fence_gate",
			"jungle_fence_gate",
			"acacia_fence_gate",
			"dark_oak_fence_gate",
			"brick_stairs",
			"stone_brick_stairs",
			"mycelium",
			"lily_pad",
			"nether_bricks",
			"nether_brick_fence",
			"nether_brick_stairs",
			"enchanting_table",
			"end_portal_frame",
			"end_stone",
			"end_stone_bricks",
			"dragon_egg",
			"redstone_lamp",
			"sandstone_stairs",
			"emerald_ore",
			"ender_chest",
			"tripwire_hook",
			"emerald_block",
			"spruce_stairs",
			"birch_stairs",
			"jungle_stairs",
			"command_block",
			"beacon",
			"cobblestone_wall",
			"mossy_cobblestone_wall",
			"brick_wall",
			"prismarine_wall",
			"red_sandstone_wall",
			"mossy_stone_brick_wall",
			"granite_wall",
			"stone_brick_wall",
			"nether_brick_wall",
			"andesite_wall",
			"red_nether_brick_wall",
			"sandstone_wall",
			"end_stone_brick_wall",
			"diorite_wall",
			"oak_button",
			"spruce_button",
			"birch_button",
			"jungle_button",
			"acacia_button",
			"dark_oak_button",
			"anvil",
			"chipped_anvil",
			"damaged_anvil",
			"trapped_chest",
			"light_weighted_pressure_plate",
			"heavy_weighted_pressure_plate",
			"daylight_detector",
			"redstone_block",
			"nether_quartz_ore",
			"hopper",
			"chiseled_quartz_block",
			"quartz_block",
			"quartz_pillar",
			"quartz_stairs",
			"activator_rail",
			"dropper",
			"white_terracotta",
			"orange_terracotta",
			"magenta_terracotta",
			"light_blue_terracotta",
			"yellow_terracotta",
			"lime_terracotta",
			"pink_terracotta",
			"gray_terracotta",
			"light_gray_terracotta",
			"cyan_terracotta",
			"purple_terracotta",
			"blue_terracotta",
			"brown_terracotta",
			"green_terracotta",
			"red_terracotta",
			"black_terracotta",
			"barrier",
			"iron_trapdoor",
			"hay_block",
			"white_carpet",
			"orange_carpet",
			"magenta_carpet",
			"light_blue_carpet",
			"yellow_carpet",
			"lime_carpet",
			"pink_carpet",
			"gray_carpet",
			"light_gray_carpet",
			"cyan_carpet",
			"purple_carpet",
			"blue_carpet",
			"brown_carpet",
			"green_carpet",
			"red_carpet",
			"black_carpet",
			"terracotta",
			"coal_block",
			"packed_ice",
			"acacia_stairs",
			"dark_oak_stairs",
			"slime_block",
			"grass_path",
			"sunflower",
			"lilac",
			"rose_bush",
			"peony",
			"tall_grass",
			"large_fern",
			"white_stained_glass",
			"orange_stained_glass",
			"magenta_stained_glass",
			"light_blue_stained_glass",
			"yellow_stained_glass",
			"lime_stained_glass",
			"pink_stained_glass",
			"gray_stained_glass",
			"light_gray_stained_glass",
			"cyan_stained_glass",
			"purple_stained_glass",
			"blue_stained_glass",
			"brown_stained_glass",
			"green_stained_glass",
			"red_stained_glass",
			"black_stained_glass",
			"white_stained_glass_pane",
			"orange_stained_glass_pane",
			"magenta_stained_glass_pane",
			"light_blue_stained_glass_pane",
			"yellow_stained_glass_pane",
			"lime_stained_glass_pane",
			"pink_stained_glass_pane",
			"gray_stained_glass_pane",
			"light_gray_stained_glass_pane",
			"cyan_stained_glass_pane",
			"purple_stained_glass_pane",
			"blue_stained_glass_pane",
			"brown_stained_glass_pane",
			"green_stained_glass_pane",
			"red_stained_glass_pane",
			"black_stained_glass_pane",
			"prismarine",
			"prismarine_bricks",
			"dark_prismarine",
			"prismarine_stairs",
			"prismarine_brick_stairs",
			"dark_prismarine_stairs",
			"sea_lantern",
			"red_sandstone",
			"chiseled_red_sandstone",
			"cut_red_sandstone",
			"red_sandstone_stairs",
			"repeating_command_block",
			"chain_command_block",
			"magma_block",
			"nether_wart_block",
			"red_nether_bricks",
			"bone_block",
			"structure_void",
			"observer",
			"shulker_box",
			"white_shulker_box",
			"orange_shulker_box",
			"magenta_shulker_box",
			"light_blue_shulker_box",
			"yellow_shulker_box",
			"lime_shulker_box",
			"pink_shulker_box",
			"gray_shulker_box",
			"light_gray_shulker_box",
			"cyan_shulker_box",
			"purple_shulker_box",
			"blue_shulker_box",
			"brown_shulker_box",
			"green_shulker_box",
			"red_shulker_box",
			"black_shulker_box",
			"white_glazed_terracotta",
			"orange_glazed_terracotta",
			"magenta_glazed_terracotta",
			"light_blue_glazed_terracotta",
			"yellow_glazed_terracotta",
			"lime_glazed_terracotta",
			"pink_glazed_terracotta",
			"gray_glazed_terracotta",
			"light_gray_glazed_terracotta",
			"cyan_glazed_terracotta",
			"purple_glazed_terracotta",
			"blue_glazed_terracotta",
			"brown_glazed_terracotta",
			"green_glazed_terracotta",
			"red_glazed_terracotta",
			"black_glazed_terracotta",
			"white_concrete",
			"orange_concrete",
			"magenta_concrete",
			"light_blue_concrete",
			"yellow_concrete",
			"lime_concrete",
			"pink_concrete",
			"gray_concrete",
			"light_gray_concrete",
			"cyan_concrete",
			"purple_concrete",
			"blue_concrete",
			"brown_concrete",
			"green_concrete",
			"red_concrete",
			"black_concrete",
			"white_concrete_powder",
			"orange_concrete_powder",
			"magenta_concrete_powder",
			"light_blue_concrete_powder",
			"yellow_concrete_powder",
			"lime_concrete_powder",
			"pink_concrete_powder",
			"gray_concrete_powder",
			"light_gray_concrete_powder",
			"cyan_concrete_powder",
			"purple_concrete_powder",
			"blue_concrete_powder",
			"brown_concrete_powder",
			"green_concrete_powder",
			"red_concrete_powder",
			"black_concrete_powder",
			"turtle_egg",
			"dead_tube_coral_block",
			"dead_brain_coral_block",
			"dead_bubble_coral_block",
			"dead_fire_coral_block",
			"dead_horn_coral_block",
			"tube_coral_block",
			"brain_coral_block",
			"bubble_coral_block",
			"fire_coral_block",
			"horn_coral_block",
			"tube_coral",
			"brain_coral",
			"bubble_coral",
			"fire_coral",
			"horn_coral",
			"dead_brain_coral",
			"dead_bubble_coral",
			"dead_fire_coral",
			"dead_horn_coral",
			"dead_tube_coral",
			"tube_coral_fan",
			"brain_coral_fan",
			"bubble_coral_fan",
			"fire_coral_fan",
			"horn_coral_fan",
			"dead_tube_coral_fan",
			"dead_brain_coral_fan",
			"dead_bubble_coral_fan",
			"dead_fire_coral_fan",
			"dead_horn_coral_fan",
			"blue_ice",
			"conduit",
			"polished_granite_stairs",
			"smooth_red_sandstone_stairs",
			"mossy_stone_brick_stairs",
			"polished_diorite_stairs",
			"mossy_cobblestone_stairs",
			"end_stone_brick_stairs",
			"stone_stairs",
			"smooth_sandstone_stairs",
			"smooth_quartz_stairs",
			"granite_stairs",
			"andesite_stairs",
			"red_nether_brick_stairs",
			"polished_andesite_stairs",
			"diorite_stairs",
			"polished_granite_slab",
			"smooth_red_sandstone_slab",
			"mossy_stone_brick_slab",
			"polished_diorite_slab",
			"mossy_cobblestone_slab",
			"end_stone_brick_slab",
			"smooth_sandstone_slab",
			"smooth_quartz_slab",
			"granite_slab",
			"andesite_slab",
			"red_nether_brick_slab",
			"polished_andesite_slab",
			"diorite_slab",
			"scaffolding",
			"iron_door",
			"oak_door",
			"spruce_door",
			"birch_door",
			"jungle_door",
			"acacia_door",
			"dark_oak_door",
			"repeater",
			"comparator",
			"structure_block",
			"jigsaw",
			"composter",
			"turtle_helmet",
			"scute",
			"iron_shovel",
			"iron_pickaxe",
			"iron_axe",
			"flint_and_steel",
			"apple",
			"bow",
			"arrow",
			"coal",
			"charcoal",
			"diamond",
			"iron_ingot",
			"gold_ingot",
			"iron_sword",
			"wooden_sword",
			"wooden_shovel",
			"wooden_pickaxe",
			"wooden_axe",
			"stone_sword",
			"stone_shovel",
			"stone_pickaxe",
			"stone_axe",
			"diamond_sword",
			"diamond_shovel",
			"diamond_pickaxe",
			"diamond_axe",
			"stick",
			"bowl",
			"mushroom_stew",
			"golden_sword",
			"golden_shovel",
			"golden_pickaxe",
			"golden_axe",
			"string",
			"feather",
			"gunpowder",
			"wooden_hoe",
			"stone_hoe",
			"iron_hoe",
			"diamond_hoe",
			"golden_hoe",
			"wheat_seeds",
			"wheat",
			"bread",
			"leather_helmet",
			"leather_chestplate",
			"leather_leggings",
			"leather_boots",
			"chainmail_helmet",
			"chainmail_chestplate",
			"chainmail_leggings",
			"chainmail_boots",
			"iron_helmet",
			"iron_chestplate",
			"iron_leggings",
			"iron_boots",
			"diamond_helmet",
			"diamond_chestplate",
			"diamond_leggings",
			"diamond_boots",
			"golden_helmet",
			"golden_chestplate",
			"golden_leggings",
			"golden_boots",
			"flint",
			"porkchop",
			"cooked_porkchop",
			"painting",
			"golden_apple",
			"enchanted_golden_apple",
			"oak_sign",
			"spruce_sign",
			"birch_sign",
			"jungle_sign",
			"acacia_sign",
			"dark_oak_sign",
			"bucket",
			"water_bucket",
			"lava_bucket",
			"minecart",
			"saddle",
			"redstone",
			"snowball",
			"oak_boat",
			"leather",
			"milk_bucket",
			"pufferfish_bucket",
			"salmon_bucket",
			"cod_bucket",
			"tropical_fish_bucket",
			"brick",
			"clay_ball",
			"sugar_cane",
			"kelp",
			"dried_kelp_block",
			"bamboo",
			"paper",
			"book",
			"slime_ball",
			"chest_minecart",
			"furnace_minecart",
			"egg",
			"compass",
			"fishing_rod",
			"clock",
			"glowstone_dust",
			"cod",
			"salmon",
			"tropical_fish",
			"pufferfish",
			"cooked_cod",
			"cooked_salmon",
			"ink_sac",
			"red_dye",
			"green_dye",
			"cocoa_beans",
			"lapis_lazuli",
			"purple_dye",
			"cyan_dye",
			"light_gray_dye",
			"gray_dye",
			"pink_dye",
			"lime_dye",
			"yellow_dye",
			"light_blue_dye",
			"magenta_dye",
			"orange_dye",
			"bone_meal",
			"blue_dye",
			"brown_dye",
			"black_dye",
			"white_dye",
			"bone",
			"sugar",
			"cake",
			"white_bed",
			"orange_bed",
			"magenta_bed",
			"light_blue_bed",
			"yellow_bed",
			"lime_bed",
			"pink_bed",
			"gray_bed",
			"light_gray_bed",
			"cyan_bed",
			"purple_bed",
			"blue_bed",
			"brown_bed",
			"green_bed",
			"red_bed",
			"black_bed",
			"cookie",
			"filled_map",
			"shears",
			"melon_slice",
			"dried_kelp",
			"pumpkin_seeds",
			"melon_seeds",
			"beef",
			"cooked_beef",
			"chicken",
			"cooked_chicken",
			"rotten_flesh",
			"ender_pearl",
			"blaze_rod",
			"ghast_tear",
			"gold_nugget",
			"nether_wart",
			"potion",
			"glass_bottle",
			"spider_eye",
			"fermented_spider_eye",
			"blaze_powder",
			"magma_cream",
			"brewing_stand",
			"cauldron",
			"ender_eye",
			"glistering_melon_slice",
			"bat_spawn_egg",
			"bee_spawn_egg",
			"blaze_spawn_egg",
			"cat_spawn_egg",
			"cave_spider_spawn_egg",
			"chicken_spawn_egg",
			"cod_spawn_egg",
			"cow_spawn_egg",
			"creeper_spawn_egg",
			"dolphin_spawn_egg",
			"donkey_spawn_egg",
			"drowned_spawn_egg",
			"elder_guardian_spawn_egg",
			"enderman_spawn_egg",
			"endermite_spawn_egg",
			"evoker_spawn_egg",
			"fox_spawn_egg",
			"ghast_spawn_egg",
			"guardian_spawn_egg",
			"horse_spawn_egg",
			"husk_spawn_egg",
			"llama_spawn_egg",
			"magma_cube_spawn_egg",
			"mooshroom_spawn_egg",
			"mule_spawn_egg",
			"ocelot_spawn_egg",
			"panda_spawn_egg",
			"parrot_spawn_egg",
			"phantom_spawn_egg",
			"pig_spawn_egg",
			"pillager_spawn_egg",
			"polar_bear_spawn_egg",
			"pufferfish_spawn_egg",
			"rabbit_spawn_egg",
			"ravager_spawn_egg",
			"salmon_spawn_egg",
			"sheep_spawn_egg",
			"shulker_spawn_egg",
			"silverfish_spawn_egg",
			"skeleton_spawn_egg",
			"skeleton_horse_spawn_egg",
			"slime_spawn_egg",
			"spider_spawn_egg",
			"squid_spawn_egg",
			"stray_spawn_egg",
			"trader_llama_spawn_egg",
			"tropical_fish_spawn_egg",
			"turtle_spawn_egg",
			"vex_spawn_egg",
			"villager_spawn_egg",
			"vindicator_spawn_egg",
			"wandering_trader_spawn_egg",
			"witch_spawn_egg",
			"wither_skeleton_spawn_egg",
			"wolf_spawn_egg",
			"zombie_spawn_egg",
			"zombie_horse_spawn_egg",
			"zombie_pigman_spawn_egg",
			"zombie_villager_spawn_egg",
			"experience_bottle",
			"fire_charge",
			"writable_book",
			"written_book",
			"emerald",
			"item_frame",
			"flower_pot",
			"carrot",
			"potato",
			"baked_potato",
			"poisonous_potato",
			"map",
			"golden_carrot",
			"skeleton_skull",
			"wither_skeleton_skull",
			"player_head",
			"zombie_head",
			"creeper_head",
			"dragon_head",
			"carrot_on_a_stick",
			"nether_star",
			"pumpkin_pie",
			"firework_rocket",
			"firework_star",
			"enchanted_book",
			"nether_brick",
			"quartz",
			"tnt_minecart",
			"hopper_minecart",
			"prismarine_shard",
			"prismarine_crystals",
			"rabbit",
			"cooked_rabbit",
			"rabbit_stew",
			"rabbit_foot",
			"rabbit_hide",
			"armor_stand",
			"iron_horse_armor",
			"golden_horse_armor",
			"diamond_horse_armor",
			"leather_horse_armor",
			"lead",
			"name_tag",
			"command_block_minecart",
			"mutton",
			"cooked_mutton",
			"white_banner",
			"orange_banner",
			"magenta_banner",
			"light_blue_banner",
			"yellow_banner",
			"lime_banner",
			"pink_banner",
			"gray_banner",
			"light_gray_banner",
			"cyan_banner",
			"purple_banner",
			"blue_banner",
			"brown_banner",
			"green_banner",
			"red_banner",
			"black_banner",
			"end_crystal",
			"chorus_fruit",
			"popped_chorus_fruit",
			"beetroot",
			"beetroot_seeds",
			"beetroot_soup",
			"dragon_breath",
			"splash_potion",
			"spectral_arrow",
			"tipped_arrow",
			"lingering_potion",
			"shield",
			"elytra",
			"spruce_boat",
			"birch_boat",
			"jungle_boat",
			"acacia_boat",
			"dark_oak_boat",
			"totem_of_undying",
			"shulker_shell",
			"iron_nugget",
			"knowledge_book",
			"debug_stick",
			"music_disc_13",
			"music_disc_cat",
			"music_disc_blocks",
			"music_disc_chirp",
			"music_disc_far",
			"music_disc_mall",
			"music_disc_mellohi",
			"music_disc_stal",
			"music_disc_strad",
			"music_disc_ward",
			"music_disc_11",
			"music_disc_wait",
			"trident",
			"phantom_membrane",
			"nautilus_shell",
			"heart_of_the_sea",
			"crossbow",
			"suspicious_stew",
			"loom",
			"flower_banner_pattern",
			"creeper_banner_pattern",
			"skull_banner_pattern",
			"mojang_banner_pattern",
			"globe_banner_pattern",
			"barrel",
			"smoker",
			"blast_furnace",
			"cartography_table",
			"fletching_table",
			"grindstone",
			"lectern",
			"smithing_table",
			"stonecutter",
			"bell",
			"lantern",
			"sweet_berries",
			"campfire",
			"honeycomb",
			"bee_nest",
			"beehive",
			"honey_bottle",
			"honey_block",
			"honeycomb_block",
	};
	
	public static final String[] ITEM_DISPLAY_NAMES = {
			"Air",
			"Stone",
			"Granite",
			"Polished Granite",
			"Diorite",
			"Polished Diorite",
			"Andesite",
			"Polished Andesite",
			"Grass Block",
			"Dirt",
			"Coarse Dirt",
			"Podzol",
			"Cobblestone",
			"Oak Planks",
			"Spruce Planks",
			"Birch Planks",
			"Jungle Planks",
			"Acacia Planks",
			"Dark Oak Planks",
			"Oak Sapling",
			"Spruce Sapling",
			"Birch Sapling",
			"Jungle Sapling",
			"Acacia Sapling",
			"Dark Oak Sapling",
			"Bedrock",
			"Sand",
			"Red Sand",
			"Gravel",
			"Gold Ore",
			"Iron Ore",
			"Coal Ore",
			"Oak Log",
			"Spruce Log",
			"Birch Log",
			"Jungle Log",
			"Acacia Log",
			"Dark Oak Log",
			"Stripped Oak Log",
			"Stripped Spruce Log",
			"Stripped Birch Log",
			"Stripped Jungle Log",
			"Stripped Acacia Log",
			"Stripped Dark Oak Log",
			"Stripped Oak Wood",
			"Stripped Spruce Wood",
			"Stripped Birch Wood",
			"Stripped Jungle Wood",
			"Stripped Acacia Wood",
			"Stripped Dark Oak Wood",
			"Oak Wood",
			"Spruce Wood",
			"Birch Wood",
			"Jungle Wood",
			"Acacia Wood",
			"Dark Oak Wood",
			"Oak Leaves",
			"Spruce Leaves",
			"Birch Leaves",
			"Jungle Leaves",
			"Acacia Leaves",
			"Dark Oak Leaves",
			"Sponge",
			"Wet Sponge",
			"Glass",
			"Lapis Lazuli Ore",
			"Lapis Lazuli Block",
			"Dispenser",
			"Sandstone",
			"Chiseled Sandstone",
			"Cut Sandstone",
			"Note Block",
			"Powered Rail",
			"Detector Rail",
			"Sticky Piston",
			"Cobweb",
			"Grass",
			"Fern",
			"Dead Bush",
			"Seagrass",
			"Sea Pickle",
			"Piston",
			"White Wool",
			"Orange Wool",
			"Magenta Wool",
			"Light Blue Wool",
			"Yellow Wool",
			"Lime Wool",
			"Pink Wool",
			"Gray Wool",
			"Light Gray Wool",
			"Cyan Wool",
			"Purple Wool",
			"Blue Wool",
			"Brown Wool",
			"Green Wool",
			"Red Wool",
			"Black Wool",
			"Dandelion",
			"Poppy",
			"Blue Orchid",
			"Allium",
			"Azure Bluet",
			"Red Tulip",
			"Orange Tulip",
			"White Tulip",
			"Pink Tulip",
			"Oxeye Daisy",
			"Cornflower",
			"Lily of the Valley",
			"Wither Rose",
			"Brown Mushroom",
			"Red Mushroom",
			"Block of Gold",
			"Block of Iron",
			"Oak Slab",
			"Spruce Slab",
			"Birch Slab",
			"Jungle Slab",
			"Acacia Slab",
			"Dark Oak Slab",
			"Stone Slab",
			"Smooth Stone Slab",
			"Sandstone Slab",
			"Cut Sandstone Slab",
			"Petrified Oak Slab",
			"Cobblestone Slab",
			"Brick Slab",
			"Stone Brick Slab",
			"Nether Brick Slab",
			"Quartz Slab",
			"Red Sandstone Slab",
			"Cut Red Sandstone Slab",
			"Purpur Slab",
			"Prismarine Slab",
			"Prismarine Brick Slab",
			"Dark Prismarine Slab",
			"Smooth Quartz",
			"Smooth Red Sandstone",
			"Smooth Sandstone",
			"Smooth Stone",
			"Bricks",
			"TNT",
			"Bookshelf",
			"Mossy Cobblestone",
			"Obsidian",
			"Torch",
			"End Rod",
			"Chorus Plant",
			"Chorus Flower",
			"Purpur Block",
			"Purpur Pillar",
			"Purpur Stairs",
			"Spawner",
			"Oak Stairs",
			"Chest",
			"Diamond Ore",
			"Block of Diamond",
			"Crafting Table",
			"Farmland",
			"Furnace",
			"Ladder",
			"Rail",
			"Cobblestone Stairs",
			"Lever",
			"Stone Pressure Plate",
			"Oak Pressure Plate",
			"Spruce Pressure Plate",
			"Birch Pressure Plate",
			"Jungle Pressure Plate",
			"Acacia Pressure Plate",
			"Dark Oak Pressure Plate",
			"Redstone Ore",
			"Redstone Torch",
			"Stone Button",
			"Snow",
			"Ice",
			"Snow Block",
			"Cactus",
			"Clay",
			"Jukebox",
			"Oak Fence",
			"Spruce Fence",
			"Birch Fence",
			"Jungle Fence",
			"Acacia Fence",
			"Dark Oak Fence",
			"Pumpkin",
			"Carved Pumpkin",
			"Netherrack",
			"Soul Sand",
			"Glowstone",
			"Jack o'Lantern",
			"Oak Trapdoor",
			"Spruce Trapdoor",
			"Birch Trapdoor",
			"Jungle Trapdoor",
			"Acacia Trapdoor",
			"Dark Oak Trapdoor",
			"Infested Stone",
			"Infested Cobblestone",
			"Infested Stone Bricks",
			"Infested Mossy Stone Bricks",
			"Infested Cracked Stone Bricks",
			"Infested Chiseled Stone Bricks",
			"Stone Bricks",
			"Mossy Stone Bricks",
			"Cracked Stone Bricks",
			"Chiseled Stone Bricks",
			"Brown Mushroom Block",
			"Red Mushroom Block",
			"Mushroom Stem",
			"Iron Bars",
			"Glass Pane",
			"Melon",
			"Vines",
			"Oak Fence Gate",
			"Spruce Fence Gate",
			"Birch Fence Gate",
			"Jungle Fence Gate",
			"Acacia Fence Gate",
			"Dark Oak Fence Gate",
			"Brick Stairs",
			"Stone Brick Stairs",
			"Mycelium",
			"Lily Pad",
			"Nether Bricks",
			"Nether Brick Fence",
			"Nether Brick Stairs",
			"Enchanting Table",
			"End Portal Frame",
			"End Stone",
			"End Stone Bricks",
			"Dragon Egg",
			"Redstone Lamp",
			"Sandstone Stairs",
			"Emerald Ore",
			"Ender Chest",
			"Tripwire Hook",
			"Block of Emerald",
			"Spruce Stairs",
			"Birch Stairs",
			"Jungle Stairs",
			"Command Block",
			"Beacon",
			"Cobblestone Wall",
			"Mossy Cobblestone Wall",
			"Brick Wall",
			"Prismarine Wall",
			"Red Sandstone Wall",
			"Mossy Stone Brick Wall",
			"Granite Wall",
			"Stone Brick Wall",
			"Nether Brick Wall",
			"Andesite Wall",
			"Red Nether Brick Wall",
			"Sandstone Wall",
			"End Stone Brick Wall",
			"Diorite Wall",
			"Oak Button",
			"Spruce Button",
			"Birch Button",
			"Jungle Button",
			"Acacia Button",
			"Dark Oak Button",
			"Anvil",
			"Chipped Anvil",
			"Damaged Anvil",
			"Trapped Chest",
			"Light Weighted Pressure Plate",
			"Heavy Weighted Pressure Plate",
			"Daylight Detector",
			"Block of Redstone",
			"Nether Quartz Ore",
			"Hopper",
			"Chiseled Quartz Block",
			"Block of Quartz",
			"Quartz Pillar",
			"Quartz Stairs",
			"Activator Rail",
			"Dropper",
			"White Terracotta",
			"Orange Terracotta",
			"Magenta Terracotta",
			"Light Blue Terracotta",
			"Yellow Terracotta",
			"Lime Terracotta",
			"Pink Terracotta",
			"Gray Terracotta",
			"Light Gray Terracotta",
			"Cyan Terracotta",
			"Purple Terracotta",
			"Blue Terracotta",
			"Brown Terracotta",
			"Green Terracotta",
			"Red Terracotta",
			"Black Terracotta",
			"Barrier",
			"Iron Trapdoor",
			"Hay Bale",
			"White Carpet",
			"Orange Carpet",
			"Magenta Carpet",
			"Light Blue Carpet",
			"Yellow Carpet",
			"Lime Carpet",
			"Pink Carpet",
			"Gray Carpet",
			"Light Gray Carpet",
			"Cyan Carpet",
			"Purple Carpet",
			"Blue Carpet",
			"Brown Carpet",
			"Green Carpet",
			"Red Carpet",
			"Black Carpet",
			"Terracotta",
			"Block of Coal",
			"Packed Ice",
			"Acacia Stairs",
			"Dark Oak Stairs",
			"Slime Block",
			"Grass Path",
			"Sunflower",
			"Lilac",
			"Rose Bush",
			"Peony",
			"Tall Grass",
			"Large Fern",
			"White Stained Glass",
			"Orange Stained Glass",
			"Magenta Stained Glass",
			"Light Blue Stained Glass",
			"Yellow Stained Glass",
			"Lime Stained Glass",
			"Pink Stained Glass",
			"Gray Stained Glass",
			"Light Gray Stained Glass",
			"Cyan Stained Glass",
			"Purple Stained Glass",
			"Blue Stained Glass",
			"Brown Stained Glass",
			"Green Stained Glass",
			"Red Stained Glass",
			"Black Stained Glass",
			"White Stained Glass Pane",
			"Orange Stained Glass Pane",
			"Magenta Stained Glass Pane",
			"Light Blue Stained Glass Pane",
			"Yellow Stained Glass Pane",
			"Lime Stained Glass Pane",
			"Pink Stained Glass Pane",
			"Gray Stained Glass Pane",
			"Light Gray Stained Glass Pane",
			"Cyan Stained Glass Pane",
			"Purple Stained Glass Pane",
			"Blue Stained Glass Pane",
			"Brown Stained Glass Pane",
			"Green Stained Glass Pane",
			"Red Stained Glass Pane",
			"Black Stained Glass Pane",
			"Prismarine",
			"Prismarine Bricks",
			"Dark Prismarine",
			"Prismarine Stairs",
			"Prismarine Brick Stairs",
			"Dark Prismarine Stairs",
			"Sea Lantern",
			"Red Sandstone",
			"Chiseled Red Sandstone",
			"Cut Red Sandstone",
			"Red Sandstone Stairs",
			"Repeating Command Block",
			"Chain Command Block",
			"Magma Block",
			"Nether Wart Block",
			"Red Nether Bricks",
			"Bone Block",
			"Structure Void",
			"Observer",
			"Shulker Box",
			"White Shulker Box",
			"Orange Shulker Box",
			"Magenta Shulker Box",
			"Light Blue Shulker Box",
			"Yellow Shulker Box",
			"Lime Shulker Box",
			"Pink Shulker Box",
			"Gray Shulker Box",
			"Light Gray Shulker Box",
			"Cyan Shulker Box",
			"Purple Shulker Box",
			"Blue Shulker Box",
			"Brown Shulker Box",
			"Green Shulker Box",
			"Red Shulker Box",
			"Black Shulker Box",
			"White Glazed Terracotta",
			"Orange Glazed Terracotta",
			"Magenta Glazed Terracotta",
			"Light Blue Glazed Terracotta",
			"Yellow Glazed Terracotta",
			"Lime Glazed Terracotta",
			"Pink Glazed Terracotta",
			"Gray Glazed Terracotta",
			"Light Gray Glazed Terracotta",
			"Cyan Glazed Terracotta",
			"Purple Glazed Terracotta",
			"Blue Glazed Terracotta",
			"Brown Glazed Terracotta",
			"Green Glazed Terracotta",
			"Red Glazed Terracotta",
			"Black Glazed Terracotta",
			"White Concrete",
			"Orange Concrete",
			"Magenta Concrete",
			"Light Blue Concrete",
			"Yellow Concrete",
			"Lime Concrete",
			"Pink Concrete",
			"Gray Concrete",
			"Light Gray Concrete",
			"Cyan Concrete",
			"Purple Concrete",
			"Blue Concrete",
			"Brown Concrete",
			"Green Concrete",
			"Red Concrete",
			"Black Concrete",
			"White Concrete Powder",
			"Orange Concrete Powder",
			"Magenta Concrete Powder",
			"Light Blue Concrete Powder",
			"Yellow Concrete Powder",
			"Lime Concrete Powder",
			"Pink Concrete Powder",
			"Gray Concrete Powder",
			"Light Gray Concrete Powder",
			"Cyan Concrete Powder",
			"Purple Concrete Powder",
			"Blue Concrete Powder",
			"Brown Concrete Powder",
			"Green Concrete Powder",
			"Red Concrete Powder",
			"Black Concrete Powder",
			"Turtle Egg",
			"Dead Tube Coral Block",
			"Dead Brain Coral Block",
			"Dead Bubble Coral Block",
			"Dead Fire Coral Block",
			"Dead Horn Coral Block",
			"Tube Coral Block",
			"Brain Coral Block",
			"Bubble Coral Block",
			"Fire Coral Block",
			"Horn Coral Block",
			"Tube Coral",
			"Brain Coral",
			"Bubble Coral",
			"Fire Coral",
			"Horn Coral",
			"Dead Brain Coral",
			"Dead Bubble Coral",
			"Dead Fire Coral",
			"Dead Horn Coral",
			"Dead Tube Coral",
			"Tube Coral Fan",
			"Brain Coral Fan",
			"Bubble Coral Fan",
			"Fire Coral Fan",
			"Horn Coral Fan",
			"Dead Tube Coral Fan",
			"Dead Brain Coral Fan",
			"Dead Bubble Coral Fan",
			"Dead Fire Coral Fan",
			"Dead Horn Coral Fan",
			"Blue Ice",
			"Conduit",
			"Polished Granite Stairs",
			"Smooth Red Sandstone Stairs",
			"Mossy Stone Brick Stairs",
			"Polished Diorite Stairs",
			"Mossy Cobblestone Stairs",
			"End Stone Brick Stairs",
			"Stone Stairs",
			"Smooth Sandstone Stairs",
			"Smooth Quartz Stairs",
			"Granite Stairs",
			"Andesite Stairs",
			"Red Nether Brick Stairs",
			"Polished Andesite Stairs",
			"Diorite Stairs",
			"Polished Granite Slab",
			"Smooth Red Sandstone Slab",
			"Mossy Stone Brick Slab",
			"Polished Diorite Slab",
			"Mossy Cobblestone Slab",
			"End Stone Brick Slab",
			"Smooth Sandstone Slab",
			"Smooth Quartz Slab",
			"Granite Slab",
			"Andesite Slab",
			"Red Nether Brick Slab",
			"Polished Andesite Slab",
			"Diorite Slab",
			"Scaffolding",
			"Iron Door",
			"Oak Door",
			"Spruce Door",
			"Birch Door",
			"Jungle Door",
			"Acacia Door",
			"Dark Oak Door",
			"Redstone Repeater",
			"Redstone Comparator",
			"Structure Block",
			"Jigsaw Block",
			"Composter",
			"Turtle Shell",
			"Scute",
			"Iron Shovel",
			"Iron Pickaxe",
			"Iron Axe",
			"Flint and Steel",
			"Apple",
			"Bow",
			"Arrow",
			"Coal",
			"Charcoal",
			"Diamond",
			"Iron Ingot",
			"Gold Ingot",
			"Iron Sword",
			"Wooden Sword",
			"Wooden Shovel",
			"Wooden Pickaxe",
			"Wooden Axe",
			"Stone Sword",
			"Stone Shovel",
			"Stone Pickaxe",
			"Stone Axe",
			"Diamond Sword",
			"Diamond Shovel",
			"Diamond Pickaxe",
			"Diamond Axe",
			"Stick",
			"Bowl",
			"Mushroom Stew",
			"Golden Sword",
			"Golden Shovel",
			"Golden Pickaxe",
			"Golden Axe",
			"String",
			"Feather",
			"Gunpowder",
			"Wooden Hoe",
			"Stone Hoe",
			"Iron Hoe",
			"Diamond Hoe",
			"Golden Hoe",
			"Wheat Seeds",
			"Wheat",
			"Bread",
			"Leather Cap",
			"Leather Tunic",
			"Leather Pants",
			"Leather Boots",
			"Chainmail Helmet",
			"Chainmail Chestplate",
			"Chainmail Leggings",
			"Chainmail Boots",
			"Iron Helmet",
			"Iron Chestplate",
			"Iron Leggings",
			"Iron Boots",
			"Diamond Helmet",
			"Diamond Chestplate",
			"Diamond Leggings",
			"Diamond Boots",
			"Golden Helmet",
			"Golden Chestplate",
			"Golden Leggings",
			"Golden Boots",
			"Flint",
			"Raw Porkchop",
			"Cooked Porkchop",
			"Painting",
			"Golden Apple",
			"Enchanted Golden Apple",
			"Oak Sign",
			"Spruce Sign",
			"Birch Sign",
			"Jungle Sign",
			"Acacia Sign",
			"Dark Oak Sign",
			"Bucket",
			"Water Bucket",
			"Lava Bucket",
			"Minecart",
			"Saddle",
			"Redstone Dust",
			"Snowball",
			"Oak Boat",
			"Leather",
			"Milk Bucket",
			"Bucket of Pufferfish",
			"Bucket of Salmon",
			"Bucket of Cod",
			"Bucket of Tropical Fish",
			"Brick",
			"Clay",
			"Sugar Cane",
			"Kelp",
			"Dried Kelp Block",
			"Bamboo",
			"Paper",
			"Book",
			"Slimeball",
			"Minecart with Chest",
			"Minecart with Furnace",
			"Egg",
			"Compass",
			"Fishing Rod",
			"Clock",
			"Glowstone Dust",
			"Raw Cod",
			"Raw Salmon",
			"Tropical Fish",
			"Pufferfish",
			"Cooked Cod",
			"Cooked Salmon",
			"Ink Sac",
			"Red Dye",
			"Green Dye",
			"Cocoa Beans",
			"Lapis Lazuli",
			"Purple Dye",
			"Cyan Dye",
			"Light Gray Dye",
			"Gray Dye",
			"Pink Dye",
			"Lime Dye",
			"Yellow Dye",
			"Light Blue Dye",
			"Magenta Dye",
			"Orange Dye",
			"Bone Meal",
			"Blue Dye",
			"Brown Dye",
			"Black Dye",
			"White Dye",
			"Bone",
			"Sugar",
			"Cake",
			"White Bed",
			"Orange Bed",
			"Magenta Bed",
			"Light Blue Bed",
			"Yellow Bed",
			"Lime Bed",
			"Pink Bed",
			"Gray Bed",
			"Light Gray Bed",
			"Cyan Bed",
			"Purple Bed",
			"Blue Bed",
			"Brown Bed",
			"Green Bed",
			"Red Bed",
			"Black Bed",
			"Cookie",
			"Map",
			"Shears",
			"Melon Slice",
			"Dried Kelp",
			"Pumpkin Seeds",
			"Melon Seeds",
			"Raw Beef",
			"Steak",
			"Raw Chicken",
			"Cooked Chicken",
			"Rotten Flesh",
			"Ender Pearl",
			"Blaze Rod",
			"Ghast Tear",
			"Gold Nugget",
			"Nether Wart",
			"Potion",
			"Glass Bottle",
			"Spider Eye",
			"Fermented Spider Eye",
			"Blaze Powder",
			"Magma Cream",
			"Brewing Stand",
			"Cauldron",
			"Eye of Ender",
			"Glistering Melon Slice",
			"Bat Spawn Egg",
			"Bee Spawn Egg",
			"Blaze Spawn Egg",
			"Cat Spawn Egg",
			"Cave Spider Spawn Egg",
			"Chicken Spawn Egg",
			"Cod Spawn Egg",
			"Cow Spawn Egg",
			"Creeper Spawn Egg",
			"Dolphin Spawn Egg",
			"Donkey Spawn Egg",
			"Drowned Spawn Egg",
			"Elder Guardian Spawn Egg",
			"Enderman Spawn Egg",
			"Endermite Spawn Egg",
			"Evoker Spawn Egg",
			"Fox Spawn Egg",
			"Ghast Spawn Egg",
			"Guardian Spawn Egg",
			"Horse Spawn Egg",
			"Husk Spawn Egg",
			"Llama Spawn Egg",
			"Magma Cube Spawn Egg",
			"Mooshroom Spawn Egg",
			"Mule Spawn Egg",
			"Ocelot Spawn Egg",
			"Panda Spawn Egg",
			"Parrot Spawn Egg",
			"Phantom Spawn Egg",
			"Pig Spawn Egg",
			"Pillager Spawn Egg",
			"Polar Bear Spawn Egg",
			"Pufferfish Spawn Egg",
			"Rabbit Spawn Egg",
			"Ravager Spawn Egg",
			"Salmon Spawn Egg",
			"Sheep Spawn Egg",
			"Shulker Spawn Egg",
			"Silverfish Spawn Egg",
			"Skeleton Spawn Egg",
			"Skeleton Horse Spawn Egg",
			"Slime Spawn Egg",
			"Spider Spawn Egg",
			"Squid Spawn Egg",
			"Stray Spawn Egg",
			"Trader Llama Spawn Egg",
			"Tropical Fish Spawn Egg",
			"Turtle Spawn Egg",
			"Vex Spawn Egg",
			"Villager Spawn Egg",
			"Vindicator Spawn Egg",
			"Wandering Trader Spawn Egg",
			"Witch Spawn Egg",
			"Wither Skeleton Spawn Egg",
			"Wolf Spawn Egg",
			"Zombie Spawn Egg",
			"Zombie Horse Spawn Egg",
			"Zombie Pigman Spawn Egg",
			"Zombie Villager Spawn Egg",
			"Bottle o' Enchanting",
			"Fire Charge",
			"Book and Quill",
			"Written Book",
			"Emerald",
			"Item Frame",
			"Flower Pot",
			"Carrot",
			"Potato",
			"Baked Potato",
			"Poisonous Potato",
			"Empty Map",
			"Golden Carrot",
			"Skeleton Skull",
			"Wither Skeleton Skull",
			"Player Head",
			"Zombie Head",
			"Creeper Head",
			"Dragon Head",
			"Carrot on a Stick",
			"Nether Star",
			"Pumpkin Pie",
			"Firework Rocket",
			"Firework Star",
			"Enchanted Book",
			"Nether Brick",
			"Nether Quartz",
			"Minecart with TNT",
			"Minecart with Hopper",
			"Prismarine Shard",
			"Prismarine Crystals",
			"Raw Rabbit",
			"Cooked Rabbit",
			"Rabbit Stew",
			"Rabbit's Foot",
			"Rabbit Hide",
			"Armor Stand",
			"Iron Horse Armor",
			"Golden Horse Armor",
			"Diamond Horse Armor",
			"Leather Horse Armor",
			"Lead",
			"Name Tag",
			"Minecart with Command Block",
			"Raw Mutton",
			"Cooked Mutton",
			"White Banner",
			"Orange Banner",
			"Magenta Banner",
			"Light Blue Banner",
			"Yellow Banner",
			"Lime Banner",
			"Pink Banner",
			"Gray Banner",
			"Light Gray Banner",
			"Cyan Banner",
			"Purple Banner",
			"Blue Banner",
			"Brown Banner",
			"Green Banner",
			"Red Banner",
			"Black Banner",
			"End Crystal",
			"Chorus Fruit",
			"Popped Chorus Fruit",
			"Beetroot",
			"Beetroot Seeds",
			"Beetroot Soup",
			"Dragon's Breath",
			"Splash Potion",
			"Spectral Arrow",
			"Tipped Arrow",
			"Lingering Potion",
			"Shield",
			"Elytra",
			"Spruce Boat",
			"Birch Boat",
			"Jungle Boat",
			"Acacia Boat",
			"Dark Oak Boat",
			"Totem of Undying",
			"Shulker Shell",
			"Iron Nugget",
			"Knowledge Book",
			"Debug Stick",
			"13 Disc",
			"Cat Disc",
			"Blocks Disc",
			"Chirp Disc",
			"Far Disc",
			"Mall Disc",
			"Mellohi Disc",
			"Stal Disc",
			"Strad Disc",
			"Ward Disc",
			"11 Disc",
			"Wait Disc",
			"Trident",
			"Phantom Membrane",
			"Nautilus Shell",
			"Heart of the Sea",
			"Crossbow",
			"Suspicious Stew",
			"Loom",
			"Banner Pattern",
			"Banner Pattern",
			"Banner Pattern",
			"Banner Pattern",
			"Banner Pattern",
			"Barrel",
			"Smoker",
			"Blast Furnace",
			"Cartography Table",
			"Fletching Table",
			"Grindstone",
			"Lectern",
			"Smithing Table",
			"Stonecutter",
			"Bell",
			"Lantern",
			"Sweet Berries",
			"Campfire",
			"Honeycomb",
			"Bee Nest",
			"Beehive",
			"Honey Bottle",
			"Honey Block",
			"Honeycomb Block",
	};
	
	public static final String[] SPAWN_EGGS = {
			"bat_spawn_egg",
			"bee_spawn_egg",
			"blaze_spawn_egg",
			"cat_spawn_egg",
			"cave_spider_spawn_egg",
			"chicken_spawn_egg",
			"cod_spawn_egg",
			"cow_spawn_egg",
			"creeper_spawn_egg",
			"dolphin_spawn_egg",
			"donkey_spawn_egg",
			"drowned_spawn_egg",
			"elder_guardian_spawn_egg",
			"enderman_spawn_egg",
			"endermite_spawn_egg",
			"evoker_spawn_egg",
			"fox_spawn_egg",
			"ghast_spawn_egg",
			"guardian_spawn_egg",
			"horse_spawn_egg",
			"husk_spawn_egg",
			"llama_spawn_egg",
			"magma_cube_spawn_egg",
			"mooshroom_spawn_egg",
			"mule_spawn_egg",
			"ocelot_spawn_egg",
			"panda_spawn_egg",
			"parrot_spawn_egg",
			"phantom_spawn_egg",
			"pig_spawn_egg",
			"pillager_spawn_egg",
			"polar_bear_spawn_egg",
			"pufferfish_spawn_egg",
			"rabbit_spawn_egg",
			"ravager_spawn_egg",
			"salmon_spawn_egg",
			"sheep_spawn_egg",
			"shulker_spawn_egg",
			"silverfish_spawn_egg",
			"skeleton_spawn_egg",
			"skeleton_horse_spawn_egg",
			"slime_spawn_egg",
			"spider_spawn_egg",
			"squid_spawn_egg",
			"stray_spawn_egg",
			"trader_llama_spawn_egg",
			"tropical_fish_spawn_egg",
			"turtle_spawn_egg",
			"vex_spawn_egg",
			"villager_spawn_egg",
			"vindicator_spawn_egg",
			"wandering_trader_spawn_egg",
			"witch_spawn_egg",
			"wither_skeleton_spawn_egg",
			"wolf_spawn_egg",
			"zombie_spawn_egg",
			"zombie_horse_spawn_egg",
			"zombie_pigman_spawn_egg",
			"zombie_villager_spawn_egg",
	};
	
	public static final File lootDir = new File("loot_nbt");
	public static final String[] LOOT_ITEMS;
	static {
		if (!lootDir.exists()) {
			lootDir.mkdir();
		}
		LOOT_ITEMS = new String[lootDir.listFiles().length];
		int i = 0;
		for (File file : lootDir.listFiles()) {
			try {
				InputStreamReader reader = new InputStreamReader(new FileInputStream(file), StandardCharsets.UTF_8);
				char charArray[] = new char[(int) file.length()];
				reader.read(charArray);
				reader.close();
				LOOT_ITEMS[i++] = new String(charArray);
			} catch (IOException e) {
				LOOT_ITEMS[i++] = "";
				e.printStackTrace();
			}
		}
	}
}
