bots:
  - host: "play.kaboom.pw"
    port: 25565
    serverNick: "Kaboom"
    discordToken: "Discord bot token goes here"
    categoryName: "Main Kaboom Channels"
    isDefault: true

trustedKey: ""
adminKey: ""
ownerKey: ""